myapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import *
from django.contrib.auth import views as auth_views
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path(r'home',views.home, name='home'),
    path(r'userInfoChange',views.userInfoChange, name='userInfoChange'),
    path(r'userInfoChange_doctor',views.userInfoChange_doctor, name='userInfoChange_doctor'),
    path(r'account',views.account, name='account'),
    path(r'patient', views.patient, name='patient'),
    path(r'patient_response', views.patient, name='patient_response'),
    path(r'doctor', views.doctor, name='doctor'),
    path(r'doctor_response', views.doctor, name='doctor_response'),
    path(r'login', views.user_login, name='user_login'),
    path(r'logout', views.user_logout, name='user_logout'),
    path(r'register', views.register, name='register'),

    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path(r'password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path(r'password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path(r'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(r'password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path(r'reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),


]

myhealthcare/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path(r'', include('myapp.urls')),
    path('', admin.site.urls),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Patient(models.Model):
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]
    user_id = models.CharField(max_length=150, null=True, blank=True)
    username = models.CharField(max_length=150, blank=True)
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20, blank=True)
    age = models.CharField(max_length=20, blank=True)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES, blank=True)
    address = models.CharField(max_length=200, blank=True)
    symptom = models.TextField(max_length=300, null=True, blank=True)

    def __str__(self):
        return "username: {}, first_name:{},last_name: {}, age:{}, gender:{}, address:{}"\
            .format(self.username, self.first_name, self.last_name, self.age, self.gender, self.address)


class Doctor(models.Model):
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]
    user_id = models.CharField(max_length=150, null=True, blank=True)
    username = models.CharField(max_length=150, blank=True)
    first_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20, blank=True)
    age = models.CharField(max_length=20, blank=True)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES, blank=True)
    address = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return "username: {}, first_name:{},last_name: {}, age:{}, gender:{}, address:{}" \
            .format(self.username, self.first_name, self.last_name, self.age, self.gender, self.address)


class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

    def __str__(self):
        return self.name

myapp/forms.py
from django import forms
from myapp.models import Patient, Doctor
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        first_name = forms.CharField(required=False)
        last_name = forms.CharField(required=False)
        age = forms.CharField(required=False)
        gender = forms.CharField(required=False)
        address = forms.CharField(required=False)
        user_id = forms.CharField(required=False)
        symptom = forms.CharField(required=False)
        fields = {'first_name', 'last_name', 'age', 'gender', 'address', 'user_id', 'symptom'}


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        first_name = forms.CharField(required=False)
        last_name = forms.CharField(required=False)
        age = forms.CharField(required=False)
        gender = forms.CharField(required=False)
        address = forms.CharField(required=False)
        user_id = forms.CharField(required=False)

        fields = {'first_name', 'last_name', 'age', 'gender', 'address', 'user_id'}


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    identity = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "identity")

    # def save(self, commit=True):
    #     user = super(UserCreationForm, self).save(commit=False)
    #     user.email = self.cleaned_data["email"]
    #     if commit:
    #         user.save()
    #     return user

myapp/views.py
from datetime import datetime
import pytz
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from myapp.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from myapp.forms import PatientForm, DoctorForm
from myapp.models import Topic, Patient, Doctor
from django.views import View


# Create your views here.

class IndexView(View):
    def get(self, request):
        if 'last_login' in request.session:
            last_login = request.session['last_login']
        else:
            last_login = "Your last login was more than one hour ago!!"
        # top_list = Topic.objects.all().order_by('id')[:10]
        # request.session.set_test_cookie()
        return render(request, 'myapp/index.html', {'ash': self.get_queryset(), 'last_login': last_login})

    def get_queryset(self):
        return Topic.objects.all().order_by('id')[:10]

def patient(request):
    msg = ''
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.save()
            msg = 'Your information has been uploaded successfully.'
        return render(request, 'myapp/patient_response.html', {'msg': msg})
    else:
        form = PatientForm()
    return render(request, 'myapp/patient.html', {'form': form, 'msg': msg})


def home(request):

    return render(request, 'myapp/home.html')


def doctor(request):
    msg = ''
    if request.method == 'POST':
        form = DoctorForm(request.POST)
        if form.is_valid():
            doctor = form.save(commit=False)
            doctor.save()
            msg = 'Your feedback has been uploaded successfully.'
        return render(request, 'myapp/doctor_response.html', {'msg': msg})
    else:
        form = DoctorForm()
    return render(request, 'myapp/doctor.html', {'form': form, 'msg': msg})


def account(request):
    return render(request, 'myapp/account.html')


def userInfoChange(request):
    if request.method == 'POST':
        form_obj = PatientForm(request.POST)
        #print(form_obj)
        if form_obj.is_valid():
            id = request.POST.get("id", "")
            patient = Patient.objects.filter(user_id=id)
            _patient = patient[0]
            oldUser = User.objects.filter(id=id)
            _oldUser = oldUser[0]

            username = request.POST.get("username", "")
            check = True
            if username:
                checkifUsername = User.objects.filter(username=username)
                if checkifUsername.count() != 0:
                    check = False
                else:
                    _patient.username = username
                    _oldUser.username = username
            email = request.POST.get("email", "")
            if email:
                #_patient.email = email
                _oldUser.email = email
            first_name = request.POST.get("first_name", "")
            if first_name:
                _patient.first_name = first_name
                _oldUser.first_name = first_name
            last_name = request.POST.get("last_name", "")
            if last_name:
                _patient.last_name = last_name
                _oldUser.last_name = last_name
            age = request.POST.get("age", "")
            if age:
                _patient.age = age
            gender = request.POST.get("gender", "")
            if gender:
                if gender == 'M':
                    _patient.gender = "M"
                    g = "Male"
                elif gender == "F":
                    _patient.gender = "F"
                    g = "Female"
            address = request.POST.get("address", "")
            if address:
                _patient.address = address

            if not check:
                return render(request, "myapp/account.html",
                              {'username': _patient.username, 'email': _oldUser.email, 'userId': id,
                               "firstname": _patient.first_name, "lastname": _patient.last_name,
                               "age": _patient.age, "gender": g, "address": _patient.address, "failed": 1})
            else:
                _patient.save()
                _oldUser.save()

                return render(request, "myapp/account.html", {'username': _patient.username, 'email': _oldUser.email, 'userId': id, "firstname": _patient.first_name, "lastname": _patient.last_name,
                                                              "age": _patient.age, "gender": g, "address": _patient.address, "failed": 0})
    return render(request, "myapp/account.html")


def userInfoChange_doctor(request):
    if request.method == 'POST':
        form_obj = DoctorForm(request.POST)
        if form_obj.is_valid():
            id = request.POST.get("id", "")
            doctor = Doctor.objects.filter(user_id=id)
            _doctor = doctor[0]
            oldUser = User.objects.filter(id=id)
            _oldUser = oldUser[0]

            username = request.POST.get("username", "")
            check = True
            if username:
                checkifUsername = User.objects.filter(username=username)
                if checkifUsername.count() != 0:
                    check = False
                else:
                    _doctor.username = username
                    _oldUser.username = username
            email = request.POST.get("email", "")
            if email:
                #_doctor.email = email
                _oldUser.email = email
            first_name = request.POST.get("first_name", "")
            if first_name:
                _doctor.first_name = first_name
                _oldUser.first_name = first_name
            last_name = request.POST.get("last_name", "")
            if last_name:
                _doctor.last_name = last_name
                _oldUser.last_name = last_name
            age = request.POST.get("age", "")
            if age:
                _doctor.age = age
            gender = request.POST.get("gender", "")
            if gender:
                if gender == 'M':
                    _doctor.gender = "M"
                    g = "Male"
                elif gender == "F":
                    _doctor.gender = "F"
                    g = "Female"
            address = request.POST.get("address", "")
            if address:
                _doctor.address = address

            if not check:
                return render(request, "myapp/doctor.html",
                              {'username': _doctor.username, 'email': _oldUser.email, 'userId': id,
                               "firstname": _doctor.first_name, "lastname": _doctor.last_name,
                               "age": _doctor.age, "gender": g, "address": _doctor.address, "failed": 1})
            else:
                _doctor.save()
                _oldUser.save()

                return render(request, "myapp/doctor.html", {'username': _doctor.username, 'email': _oldUser.email, 'userId': id, "firstname": _doctor.first_name, "lastname": _doctor.last_name,
                                                              "age": _doctor.age, "gender": g, "address": _doctor.address, "failed": 0})
    return render(request, "myapp/doctor.html")



def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        current_login_time = datetime.now(pytz.timezone('America/Toronto'))
        timestamp = current_login_time.strftime("%d-%b-%Y (%H:%M:%S)")
        request.session['last_login'] = 'Last Login: ' + timestamp
        request.session.set_expiry(60)
        if user:
            login(request, user)
            # if 'next' in request.POST:
            #     return redirect(request.POST.get('next'))
            # else:

            # 判断是医生还是病人
            # 是医生
            if user.identity == '1':
                doctor = Doctor.objects.filter(user_id=user.id)
                message = 'click to update'
                if doctor.count() != 0:
                    if doctor[0].first_name:
                        firstname = doctor[0].first_name
                    else:
                        firstname = message
                    if doctor[0].last_name:
                        lastname = doctor[0].last_name
                    else:
                        lastname = message
                    if doctor[0].age:
                        age = doctor[0].age
                    else:
                        age = message
                    if doctor[0].address:
                        address = doctor[0].address
                    else:
                        address = message
                    if doctor[0].gender == 'M':
                        gender = "Male"
                    elif doctor[0].gender == 'F':
                        gender = "Female"
                    else:
                        gender = message
                else:
                    firstname = message
                    lastname = message
                    age = message
                    gender = message
                    address = message
                return render(request, 'myapp/doctor.html', {'username': user.username, 'email': user.email,
                                                              'userId': user.id, "firstname": firstname,
                                                              "lastname": lastname,
                                                              "age": age, "gender": gender, "address": address})
            # 病人
            else:
                patient = Patient.objects.filter(user_id=user.id)
                message = 'click to update'
                if patient.count() != 0:

myapp/templates/myapp/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/myapp/CSS/account.css">
    <title>My account</title>
</head>
<body>
    <p id="error" style="display: none">{{ failed }}</p>
    <p id="username" style="display: none">{{ username }}</p>
    <p id="email" style="display: none">{{ email }}</p>
    <div id="mask"></div>
    <div id="title">
        <h1></h1>
        <p id="time"></p>
        <br>
        <p id="message">The username has been existed.</p>
    </div>

    <span id="logout"> <a href="{% url 'myapp:user_logout' %}"> log out</a></span>
    <div id="navigation">
        <div class="naviItems" value="1" style="background-color:  rgba(0, 0, 0, 0.3);">Personal information</div>
        <div class="naviItems" value="2">Patient field</div>
        <div class="naviItems" value="3">Patient field</div>
        <div class="naviItems" value="4">Patient field</div>
    </div>
    <div id="showArea">

        <div class="shownItems" value="1" style="display: block;">
            <form action="{% url 'myapp:userInfoChange' %}" method="post">
                {% csrf_token %}
             <div style="display: none"><input name="id" type="text" value="{{ userId }}"></div>
             <div id="notepart">
                <div id="uname" class="left">Username:</div><br><br>
                <div id="email" class="left">Email:</div><br><br>
                <div id="firstname" class="left">First name:</div><br><br>
                <div id="lastname" class="left">Last name:</div><br><br>
                <div id="age" class="left">Age:</div><br><br>
                <div id="gender" class="left">Gender:</div><br><br>
                <div id="address" class="left">Address:</div><br><br>
             </div>


            <div id="inputpart">
                <input id="uninput" class="right" style="display: none" type="input" name="username" placeholder="{{ username }}">
                 <a href="javascript:void(0);" class="right" onclick="showusername()" id="changeUname">{{ username }}</a>
                <br><br>

                <input id="emailinput" class="right" style="display: none" type="input" name="email" placeholder="{{ email }}">
                <a href="javascript:void(0);" class="right" onclick="showemail()" id="changeEma" >{{ email }}</a>
                <br><br>

                <input id="fninput" class="right" style="display: none" type="input" name="first_name" placeholder="{{ firstname }}">
                <a href="javascript:void(0);" class="right" onclick="showfirstname()" id="changefn" >{{ firstname }}</a>
                <br><br>

                <input id="lninput" class="right" style="display: none" type="input" name="last_name" placeholder="{{ lastname }}">
                <a href="javascript:void(0);" class="right" onclick="showlastname()" id="changeln" >{{ lastname }}</a>
                <br><br>

                <input id="ageinput" class="right" style="display: none" type="input" name="age" placeholder="{{ age }}">
                <a href="javascript:void(0);" class="right"  onclick="showage()" id="changeage" >{{ age }}</a>
                <br><br>

                <select id="genderselect" style="display: none" class="right" name="gender">
                   <option value="M">Male</option>
                   <option value="F">Female</option>
                </select>
                <a href="javascript:void(0);" class="right"  onclick="showgender()" id="changegender" >{{ gender }}</a>
                <br><br>

                <input id="addrinput" class="right" style="display: none" type="input" name="address" placeholder="{{ address }}">
                 <a href="javascript:void(0);" class="right" onclick="showaddr()" id="changeaddr" >{{ address }}</a>

            </div>
               <div id="submit"><input type="submit" value="OK" id="subtn" name="submit1"></div>
            </form>
        </div>
        <div class="shownItems" value="2">this is the area for item2 of patients</div>
        <div class="shownItems" value="3">this is the area for item3 of patients</div>
        <div class="shownItems" value="4">this is the area for item4 of patients</div>
    </div>
    <div id="appointments">No appointment currently</div>
</body>
<script src="../../static/myapp/js/jquery-1.10.1.js"></script>
<script src="../../static/myapp/js/account.js"></script>
</html>

myapp/templates/myapp/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'myapp:activate' uidb64=uid token=token %}
{% endautoescape %}

myapp/templates/myapp/account_activation_invalid.html
{#  #}
{#{% extends 'base.html' %}#}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

myapp/templates/myapp/account_activation_sent.html
{#{% extends 'myapp/base.html' %}#}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>

<html lang=en>
{% load static %}
 <head>
	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

{% include 'myapp/snippets/header.html' %}

 <div class="main">

    <br>
	{% block body_block %} {% endblock %}
</div>
<!-- End Body -->

{% include 'myapp/snippets/footer.html' %}


 </body>
</html>

myapp/templates/myapp/doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/myapp/CSS/account.css">
    <title>My account</title>
</head>
<body>
    <p id="error" style="display: none">{{ failed }}</p>
    <p id="username" style="display: none">{{ username }}</p>
    <p id="email" style="display: none">{{ email }}</p>
    <div id="mask"></div>
    <div id="title">
        <h1></h1>
        <p id="time"></p>
        <br>
        <p id="message">The username has been existed.</p>
    </div>

    <span id="logout"> <a href="{% url 'myapp:user_logout' %}"> log out</a></span>
    <div id="navigation">
        <div class="naviItems" value="1" style="background-color:  rgba(0, 0, 0, 0.3);">Personal information</div>
        <div class="naviItems" value="2">Doctor field</div>
        <div class="naviItems" value="3">Doctor field</div>
        <div class="naviItems" value="4">Doctor field</div>
    </div>
    <div id="showArea">

        <div class="shownItems" value="1" style="display: block;">
            <form action="{% url 'myapp:userInfoChange_doctor' %}" method="post">
                {% csrf_token %}
             <div style="display: none"><input name="id" type="text" value="{{ userId }}"></div>
             <div id="notepart">
                <div id="uname" class="left">Username:</div><br><br>
                <div id="email" class="left">Email:</div><br><br>
                <div id="firstname" class="left">First name:</div><br><br>
                <div id="lastname" class="left">Last name:</div><br><br>
                <div id="age" class="left">Age:</div><br><br>
                <div id="gender" class="left">Gender:</div><br><br>
                <div id="address" class="left">Address:</div><br><br>
             </div>


            <div id="inputpart">
                <input id="uninput" class="right" style="display: none" type="input" name="username" placeholder="{{ username }}">
                 <a href="javascript:void(0);" class="right" onclick="showusername()" id="changeUname">{{ username }}</a>
                <br><br>

                <input id="emailinput" class="right" style="display: none" type="input" name="email" placeholder="{{ email }}">
                <a href="javascript:void(0);" class="right" onclick="showemail()" id="changeEma" >{{ email }}</a>
                <br><br>

                <input id="fninput" class="right" style="display: none" type="input" name="first_name" placeholder="{{ firstname }}">
                <a href="javascript:void(0);" class="right" onclick="showfirstname()" id="changefn" >{{ firstname }}</a>
                <br><br>

                <input id="lninput" class="right" style="display: none" type="input" name="last_name" placeholder="{{ lastname }}">
                <a href="javascript:void(0);" class="right" onclick="showlastname()" id="changeln" >{{ lastname }}</a>
                <br><br>

                <input id="ageinput" class="right" style="display: none" type="input" name="age" placeholder="{{ age }}">
                <a href="javascript:void(0);" class="right"  onclick="showage()" id="changeage" >{{ age }}</a>
                <br><br>

                <select id="genderselect" style="display: none" class="right" name="gender">
                   <option value="M">Male</option>
                   <option value="F">Female</option>
                </select>
                <a href="javascript:void(0);" class="right"  onclick="showgender()" id="changegender" >{{ gender }}</a>
                <br><br>

                <input id="addrinput" class="right" style="display: none" type="input" name="address" placeholder="{{ address }}">
                 <a href="javascript:void(0);" class="right" onclick="showaddr()" id="changeaddr" >{{ address }}</a>

            </div>
               <div id="submit"><input type="submit" value="OK" id="subtn" name="submit1"></div>
            </form>
        </div>
        <div class="shownItems" value="2">this is the area for item2 of doctors</div>
        <div class="shownItems" value="3">this is the area for item3 of doctors</div>
        <div class="shownItems" value="4">this is the area for item4 of doctors</div>
    </div>
    <div id="appointments">No appointment currently</div>
</body>
<script src="../../static/myapp/js/jquery-1.10.1.js"></script>
<script src="../../static/myapp/js/account.js"></script>
</html>

myapp/templates/myapp/doctor_response.html
{% extends 'myapp/base.html' %}
{% block myhdg %}
	<h1>Hello {{ user.get_username }} </h1>
{% endblock %}
{% block body_block %}
	<form action="{% url 'myapp:doctor_response' %}" method="get" class="container-fluid">
    <body>
        {% csrf_token %}
        {{ form.as_p }}
		
		
        <h2>{{ msg }}! </h2>

        <a href="{% url 'myapp:doctor' %}">back</a>
    </body>
{% endblock %}

myapp/templates/myapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/myapp/CSS/home.css">
    <title>Login and Register</title>
</head>
<body>

    <div id="wrapper" style="margin-top: -196px">
        <div id="content">
         <div class="item" style="color: darkseagreen; display: block">Focus</div>
         <div class="item" style="display: block">On</div>
         <div class="item" style="color: cornflowerblue; display: block">Your</div>
         <div class="item" style="display: block">Health.</div>
        </div>
    </div>
    <div id="start" style="display: block">Start NOW!</div>
    <div id="login" ><a style="display: block" id="login-a" href="javascript:;">Login</a></div>
    <div id="register"><a  style="display: block; left: 1065.2px" id="register-a" href="javascript:;">Register</a></div>

    <div id="bgContainer">
        <video id="bg" autoplay muted loop>
            <source src="../../static/myapp/img/5s.mp4">
            <embed src="../../static/myapp/img/5s.mp4" type="video/mp4">
        </video>
    </div>


</body>
<script src="../../static/myapp/js/jquery-1.10.1.js"></script>
<script src="../../static/myapp/js/home01.js"></script>
</html>

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/myapp/CSS/home.css">
    <title>Welcome!</title>
</head>
<body>
    <div id="wrapper">
        <div id="content">
         <div class="item" style="color: darkseagreen;">Focus</div>
         <div class="item">On</div>
         <div class="item" style="color: cornflowerblue;">Your</div>
         <div class="item">Health.</div>
        </div>
    </div>
    <div id="start">Start NOW!</div>
    <div id="login"><a id="login-a" href="javascript:;">Login</a></div>
    <div id="register"><a id="register-a" href="javascript:;">Register</a></div>



    <div id="bgContainer">
        <video id="bg" autoplay muted loop>
            <source src="../../static/myapp/img/5s.mp4">
            <embed src="../../static/myapp/img/5s.mp4" type="video/mp4">
        </video>
    </div>
   
    
</body>
<script src="../../static/myapp/js/jquery-1.10.1.js"></script>
<script src="../../static/myapp/js/home.js"></script>
</html>

myapp/templates/myapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="../../static/myapp/CSS/login.css">
</head>

<body>
    {% if msg is True %}
        <p id="confirm" style="display: none;">true</p>
    {% else %}
        <p id="confirm" style="display: none;">false</p>
    {% endif %}

    <div id="login"><a id="login-a" disabled="true"  href="javascript:;">Login</a></div>
    <div id="invalid">Invalid username or password<br>Please try again</div>

    <form action="{% url 'myapp:user_login' %}" method="post" id="loginForm">
        {% csrf_token %}
        <div id="uname" class="Lform"> Username:<br><input type="input" name="username" required></div>
        <div id="pwd" class="Lform"> Password:<br><input type="password" name="password" required></div>
        <div id="submit" class="Lform"><input type="submit" value="OK" id="subtn" name="submit1"></div>

    </form>
</body>
<script src="../../static/myapp/js/jquery-1.10.1.js"></script>
<script>
    $('#loginForm').fadeIn(1000);
    var $con = $('#confirm').html();
    console.log($con)
    console.log($con == 'true')
    if($con == 'true'){
        $('#invalid').fadeIn(1000);
    }
    $('input').click(function () {
        $('#invalid').fadeOut(1000);
    });
</script>
</html>

myapp/templates/myapp/patient.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
	<body>
		<form action="{% url 'myapp:patient' %}" method="post" class="container-fluid">
		{% csrf_token %}
		 <label><b>Condition Report for: </b></label> <input type="text">
        {{ form|crispy}}
        <input type="submit" class="btn btn-info" name="submit1" value="Submit" />
		
		</form>
	</body>
{% endblock %}

myapp/templates/myapp/patient_response.html
{% extends 'myapp/base.html' %}
{% block myhdg %}
	<h1>Hello {{ user.get_username }} </h1>
{% endblock %}
{% block body_block %}
	<form action="{% url 'myapp:patient_response' %}" method="get" class="container-fluid">
    <body>
        {% csrf_token %}
        {{ form.as_p }}
		
		
        <h2>{{ msg }}! </h2>

        <a href="{% url 'myapp:patient' %}">back</a>
    </body>
{% endblock %}